### ISSUE TITLE
ゲリラ：参加時間を設定したコマンドメッセージが消えた際に正常にゲリラ攻撃できない問題

### ISSUE THREAD

**Issue by merunno** [approvers/OreOreBot2#106]
恐らくゲリラ参加時にゲリラ参加時間を設定したコマンドメッセージに対してReply Messageを行うため、削除されたメッセージにリプライしようとするにも見つからずエラーが発生している模様

![image](https://user-images.githubusercontent.com/82575685/161033337-62e9ebe4-d723-481e-bc84-281a752111e2.png)

```
DiscordAPIError: Invalid Form Body
message_reference: Unknown message
　　at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
　　at processTicksAndRejections (node:internal/process/task_queues:96:5)
　　at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
　　at async TextChannel.send (/app/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:175:15)
　　at async Object.reply (/app/build/adaptor/transformer/message-convert.js:35:25)
　　at async PartyCommand.startPartyImmediately (/app/build/service/party.js:132:9)
　　at async /app/build/service/party.js:147:13
　　at async /app/build/runner/schedule.js:37:36 {
method: 'post',
path: '/channels/690909527461199922/messages',
code: 50035,
httpStatus: 400,
requestData: {
　　json: {
　　　　content: undefined,
　　　　tts: false,
　　　　nonce: undefined,
　　　　embeds: [Array],
　　　　components: undefined,
　　　　username: undefined,
　　　　avatar_url: undefined,
　　　　allowed_mentions: undefined,
　　　　flags: 0,
　　　　message_reference: [Object],
　　　　attachments: undefined,
　　　　sticker_ids: undefined
　　　　},
　　files: []
}
```

**Comment by MikuroXina** [comment]
安全装置としては, 起動コマンドが削除された場合はゲリラ Party すべきではないので, 動作としては問題ありません.

**Comment by merunno** [comment]
ok
