### ISSUE TITLE
yarn format 実行時に Prettier が Internal Error を吐く

### ISSUE THREAD

**Issue by m1sk9** [approvers/OreOreBot2#937]
monorepo 移行後から発生

```shell
cd docs
yarn format
```

```shell
Internal Error: spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at FK (/Users/m1sk9/.cache/node/corepack/yarn/3.4.1/yarn.js:4:7031)
    at Mf.implementation (/Users/m1sk9/.cache/node/corepack/yarn/3.4.1/yarn.js:392:17802)
    at Mf.exec (/Users/m1sk9/.cache/node/corepack/yarn/3.4.1/yarn.js:395:1585)
    at Mf.run (/Users/m1sk9/.cache/node/corepack/yarn/3.4.1/yarn.js:395:1756)
    at YV (/Users/m1sk9/.cache/node/corepack/yarn/3.4.1/yarn.js:401:6331)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IDe (/Users/m1sk9/.cache/node/corepack/yarn/3.4.1/yarn.js:403:16)
    at async o (/Users/m1sk9/.cache/node/corepack/yarn/3.4.1/yarn.js:403:146)
```

**Comment by m1sk9** [comment]
はらちょ側の Prettier は問題なく動くのでドキュメント側の問題

やっぱり yarn workspace 使ってみるかぁ〜
